### ISSUE TITLE
Adjustable size for the checkbox

### ISSUE THREAD

**Issue by guifcoelho** [romanrei/vue-material-checkbox#1]
I have just found your awesome checkbox component and I intend to use it on my project. It was exactly what I was looking for. There is just one minor issue that I want to address here.

Could you provide a prop to let me choose the size of the checkbox? Going through the source files, I found out that you set it's size directly on the style, so I guess it will not be that much of a problem.

Best regards!

**Comment by xrei** [comment]
Implemented in #2
